/// Generated by AssetsRefGenerator on 2021/08/25
class Res {
  static const String authButton = "assets/images/authButton.png";
  static const String avatar = "assets/images/avatar.jpg";
  static const String background = "assets/images/background.png";
  static const String catShirt = "assets/images/catShirt.png";
  static const String facebook = "assets/images/facebook.png";
  static const String google = "assets/images/google.png";
  static const String hoodie = "assets/images/hoodie.png";
  static const String hoodie2 = "assets/images/hoodie2.png";
  static const String img1 = "assets/images/img1.png";
  static const String img2 = "assets/images/img2.png";
  static const String img3 = "assets/images/img3.png";
  static const String instagram = "assets/images/instagram.png";
  static const String shoes = "assets/images/shoes.png";
  static const String shoes2 = "assets/images/shoes2.png";
  static const String shoes3 = "assets/images/shoes3.png";
  static const String tshirt1 = "assets/images/tshirt1.png";
  static const String watch = "assets/images/watch.png";
  static const String watch2 = "assets/images/watch2.png";
}
